### ISSUE TITLE
How do I forward a CAN interface over network

### ISSUE THREAD

**Issue by daravi** [linux-can/socketcand#15]
I hope it is ok to ask here.

Using `socketcand`, is there a way to set up a virtual CAN that receives data from a physical CAN over the network and behaves like the physical CAN?

Basically I have a remote device with a CAN port, and I want to connect to and read from the CAN port as if it is on my local machine.

**Comment by yegorich** [comment]
Take a look at https://github.com/mguentner/cannelloni

**Comment by daravi** [comment]
@yegorich Thank you very much!
