### ISSUE TITLE
$ make install - kali Linux - don't know how to proceed after running 

### ISSUE THREAD

**Issue by Morsmalleo** [linux-can/socketcand#20]
This is more a question than an issue because everything else for the installation ran perfectly, just don't know what to do here when I run **make install** when this shows up, any advice?? would i just type **make install=y/make install=n** or is it done differently??

```
mkdir -p /usr/local/bin
cp ./socketcand /usr/local/bin/
cp ./socketcandcl /usr/local/bin/
mkdir -p /usr/local/share/man
cp ./socketcand.1 /usr/local/share/man/
mkdir -p /etc/
install -m 0644 ./etc/socketcand.conf /etc/
if [ yes = yes ]; then mkdir -p /etc/init.d; install --mode=755 ./init.d/socketcand /etc/init.d/socketcand; fi
if [ no = yes ]; then install --mode=755 ./rc.d/socketcand /etc/rc.d/socketcand; fi
```

**Comment by marckleinebudde** [comment]
Hey @Morsmalleo,

I've slightly edited your output, to preserve the line breaks.

You are probably wandering about the last two lines?
This is the installation of the init script and the rc script.
By default only the init script is installed, the rc script isn't.
You can change this with the `configure` options.
Use `./configure --help` to get an overview of the available options.
e.g. use `./configure --enable-rc-script` to enable the rc script installation.

What you need depends on the init system used on kali Linux.
Most modern Linux distributions use systemd these days,
but socketcand doesn't provide a systemd unit file yet.

**Comment by Morsmalleo** [comment]
Thanks man, I'll give this a try :)

**Comment by marckleinebudde** [comment]
I'll close this issue, reopen if needed.
