### ISSUE TITLE
build error on widnows

### ISSUE THREAD

**Issue by mbraeunlein** [linux-can/socketcand#25]
Trying to build this project on windows 10.
JDK version is 19.0.1 2022-10-18
Maven version is Apache Maven 3.8.6

Error message:
[ERROR] Failed to execute goal org.apache.netbeans.utilities:nbm-maven-plugin:4.2:cluster-app (default-cluster-app) on project application: Execution default-cluster-app of goal org.apache.netbeans.utilities:nbm-maven-plugin:4.2:cluster-app failed: A required class was missing while executing org.apache.netbeans.utilities:nbm-maven-plugin:4.2:cluster-app: java/util/jar/Pack200
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>org.apache.netbeans.utilities:nbm-maven-plugin:4.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Michael/.m2/repository/org/apache/netbeans/utilities/nbm-maven-plugin/4.2/nbm-maven-plugin-4.2.jar
[ERROR] urls[1] = file:/C:/Users/Michael/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[2] = file:/C:/Users/Michael/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[3] = file:/C:/Users/Michael/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[4] = file:/C:/Users/Michael/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[5] = file:/C:/Users/Michael/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/C:/Users/Michael/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5/maven-plugin-annotations-3.5.jar
[ERROR] urls[7] = file:/C:/Users/Michael/.m2/repository/org/apache/ant/ant/1.10.5/ant-1.10.5.jar
[ERROR] urls[8] = file:/C:/Users/Michael/.m2/repository/org/apache/ant/ant-launcher/1.10.5/ant-launcher-1.10.5.jar
[ERROR] urls[9] = file:/C:/Users/Michael/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[ERROR] urls[10] = file:/C:/Users/Michael/.m2/repository/org/codehaus/plexus/plexus-archiver/3.5/plexus-archiver-3.5.jar
[ERROR] urls[11] = file:/C:/Users/Michael/.m2/repository/org/apache/commons/commons-compress/1.14/commons-compress-1.14.jar
[ERROR] urls[12] = file:/C:/Users/Michael/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[ERROR] urls[13] = file:/C:/Users/Michael/.m2/repository/org/tukaani/xz/1.6/xz-1.6.jar
[ERROR] urls[14] = file:/C:/Users/Michael/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[15] = file:/C:/Users/Michael/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[16] = file:/C:/Users/Michael/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.11.1/maven-dependency-analyzer-1.11.1.jar
[ERROR] urls[17] = file:/C:/Users/Michael/.m2/repository/org/ow2/asm/asm/7.0/asm-7.0.jar
[ERROR] urls[18] = file:/C:/Users/Michael/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar
[ERROR] urls[19] = file:/C:/Users/Michael/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar
[ERROR] urls[20] = file:/C:/Users/Michael/.m2/repository/org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar
[ERROR] urls[21] = file:/C:/Users/Michael/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
[ERROR] urls[22] = file:/C:/Users/Michael/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[23] = file:/C:/Users/Michael/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[24] = file:/C:/Users/Michael/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[25] = file:/C:/Users/Michael/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[26] = file:/C:/Users/Michael/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[27] = file:/C:/Users/Michael/.m2/repository/org/apache/netbeans/utilities/nbm-maven-harness/11.0/nbm-maven-harness-11.0.jar
[ERROR] urls[28] = file:/C:/Users/Michael/.m2/repository/org/codehaus/plexus/plexus-io/3.0.0/plexus-io-3.0.0.jar
[ERROR] urls[29] = file:/C:/Users/Michael/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[30] = file:/C:/Users/Michael/.m2/repository/org/apache/netbeans/utilities/nb-shared/1.3/nb-shared-1.3.jar
[ERROR] urls[31] = file:/C:/Users/Michael/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by marckleinebudde** [comment]
I think you picked the wrong project for your issue.
