### ISSUE TITLE
error: cannot find input file: `config.h.in'

### ISSUE THREAD

**Issue by argan719** [linux-can/socketcand#30]
error: cannot find input file: `config.h.in'
![Screenshot from 2024-05-16 15-44-00](https://github.com/linux-can/socketcand/assets/64789601/20e1f448-e69e-4be8-9abd-eaf9f32001ad)

$ git clone https://github.com/linux-can/socketcand.git
$ cd socketcand
$ autoconf
$ ./configure
$ make clean
$ make

After make 
this error occured.

**Comment by marckleinebudde** [comment]
try `./autogen.sh` instead of `autoconf`.
