### ISSUE TITLE
debian package request

### ISSUE THREAD

**Issue by olerem** [linux-can/socketcand#6]
Hi,

I noticed there is no debian package for socketcand. Is it correct?
If there is no package, @ukleinek, may be you can help here?

**Comment by yegorich** [comment]
Adding @ gerasiov to the discussion.

**Comment by hartkopp** [comment]
After moving the repository to https://github.com/linux-can/socketcand and marking the source repos from @dschanoeh and @hartkopp to be obsolete three weeks ago we only have 7 stars and 3 forks.

@olerem Do you really think the socketcand is that cool and widely used, that it makes sense to make it a Debian package right now?

**Comment by olerem** [comment]
@hartkopp , i discovered it for me just this week. It helps me with j1939 tests on remote system. No idea if any one else is using it.

**Comment by yegorich** [comment]
@olerem have you also tried https://github.com/mguentner/cannelloni?

**Comment by olerem** [comment]
@yegorich, no. looks like there is no debian package as well. So, which one is better and why?

**Comment by yegorich** [comment]
@olerem I haven't compared the two but I can remeber having problems with sending a stream of CAN frames over socketcand. So it is still not suitable for a high bandwidth communcation. But sniffing with Kayak was not a problem.

**Comment by Timple** [comment]
> we only have 7 stars and 3 forks.

Up to 76 stars and 27 forks. Does that make a difference?

I think releasing this as a debian package could increase the userbase quickly. I know it lowers my threshold to test new projects.

**Comment by marckleinebudde** [comment]
Looking at @ukleinek :smile:

**Comment by marckleinebudde** [comment]
Hey @gerasiov,

do you have interest in adding this tool to debian? Otherwise @ukleinek can take over.

**Comment by RobbertBrand** [comment]
+1

Please with the "--with-config=yes" option.

Would you recommend this tool for production systems?

**Comment by ngehrsitz** [comment]
Is this something that is already included somewhere? The [can-utils](https://packages.debian.org/de/bookworm/can-utils) package already includes socketcand in the description but does not actually ship it?

**Comment by faisal-shah** [comment]
> +1
> 
> Please with the "--with-config=yes" option.
> 
> Would you recommend this tool for production systems?

As is - probably would not generally promote for production. It's a useful (and in some cases necessary) development tool. Production systems will require handling the CAN interfaces going up and down, etc.. Perhaps socketcand, in addition to some other higher level monitoring application could be production-worthy. It all comes down to your requirements :). Also, it has not been designed for security or a potential adversarial/uncontrolled environment.

Thought I would reply to this in case anyone else has the same question.

**Comment by jobcespedes** [comment]
> As is - probably would not generally promote for production. It's a useful (and in some cases necessary) development tool. Production systems will require handling the CAN interfaces going up and down, etc.. Perhaps socketcand, in addition to some other higher level monitoring application could be production-worthy. It all comes down to your requirements :). Also, it has not been designed for security or a potential adversarial/uncontrolled environment.

Is this still relevant and `socketcand` not production-ready?

**Comment by olerem** [comment]
I would not consider any can-utils as designed for production environment. But, this community is alive for long time and bugs are usually fixed. So, if some one seeing 'socketcand' as usable, I would not prevent them from packaging it. May be it will give this additional kick to move this project forward ;)

**Comment by yegorich** [comment]
The first step would opeining a packaging request (RFP) here: https://wnpp.debian.net.
